name: Deploy
on: 
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull latest tag via SSH
        uses: appleboy/ssh-action@v1.2.1
        env:
          DIR: ${{ secrets.PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: DIR
          script: |
            cd $DIR
            git pull --tags origin release
            git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
            git status
