name: Deploy
on: 
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  deploy:
    name: SSH
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout latest tag
        uses: appleboy/ssh-action@v1.2.1
        env:
          DIR: ${{ secrets.PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          envs: DIR
          script: |
            cd $(echo $DIR | tr -d '\r')
            git pull --tags origin release
            git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
            git status
